### ISSUE TITLE
feat(Print Order): Closing and WIP/FG stock transfer to Scrap WH

### ISSUE THREAD

**Issue by SaiFi0102** [ParaLogicTech/textile#42]
**Example Scenario:**

- Ordered Print Qty may be 100 Meter
- Ordered Fabric Qty may be 110 Meter

**Production Problem:**

- Fabric is transferred based on Fabric Qty (110 Meter) to the WIP warehouse (to allow overproduction and wastage)
- Fabric is consumed based on Print Qty (100 Meter)
- ~10 Meter is left after Production in the WIP warehouse

**Packing Problem:**

- Packing Qty may be different from Produced Qty as Packed Qty is measured and rounded whereas Produced Qty is calculated
- Packed Qty may be 95 Meter
- Leaving 5 meters in Finished Goods warehouse

**Status Problem:**

- If under production is greater than the allowed Under Production % configured then status will never become completed
- For example: Ordered Print of 100 Meter, Produced 80 Meter and packed 78 Meter
- For example: Ordered Print of 100 Meter, Produced 100 Meter and packed 85 Meter

**Solution:**

- Button to close Print Orders
- System to create Stock Adjustment/Transfer entries to zero out any remainder WIP or Finished Goods stock
- Stock Out Qty for WIP: Fabric Transferred Qty - Produced Qty
- Stock Out Qty for Finished Goods: Produced Qty - Packed/Delivered Qty
- System to set status as "Closed" preventing ANY further action on the Print Order

**Comment by abid-omar** [comment]
For Printed Fabric, difference between Produced Quantity and Packed Quantity to be moved into Scrap Warehouse. This difference to be manually entered, as some is unaccounted for due to other/unknown Process Wastages.

For example

**Production**
100 meter Order Quantity (fabric transferred to WIP)
90 meter Printed Fabric
10 meters remains in WIP, could be calculated 5% Process Wastages or other/unknown reasons.

**Packing**
80 Meters Packed Quantity
5 Meters Return Fabric
10 Meters is moved to Scrap Warehouse (difference between Packed and Printed)

**WIP Warehouse**
5 Meters is remaining in WIP (not Printed, not Returned)
How to handle this last 5 meters? Is it a Customer Item, or will this be Scrapped?

**Comment by SaiFi0102** [comment]
FG Scrap Qty = `Produced Qty - Packed Qty` (Printed Fabric Items)
WIP Scrap Qty = `Fabric Transferred Qty - Produced Qty - Returned Qty` (Ready Fabric Item)

FG Scrap Qty can be moved to Scrap Warehouse as you suggested without any doubt.

WIP Scrap Qty includes Ready Fabrics that were neither consumed nor returned. We can either move them to Scrap Warehouse or remove them from the system by doing a stock out. That you should decide.

Both scrap qty values **must** be a calculated value at the time of closing. Our goal is to zero out any remaining stock from WIP/FG warehouse. Therefore they should not be editable by the user because if the user is allowed to change any of these calculated values then we'll have left over stock in either WIP or FG warehouse.

**Comment by abid-omar** [comment]
Will see this in operation.

**Comment by SaiFi0102** [comment]
Will evaluate after more usage of Fabric Ledger
